{% set name = "phono3py" %}
{% set version = "2.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e1450b3145abcfc48be20634de09db91066a7e8664a819b3c01e6c551647afb2

build:
  number: 0
  script: export PHONO3PY_USE_CMAKE=false && echo "extra_compile_args = -fopenmp" > site.cfg && echo "extra_link_args = -lgomp -lopenblas" >> site.cfg && {{ PYTHON }} -m pip install . -vvv  # [linux]
  script: export PHONO3PY_USE_CMAKE=false && echo "extra_compile_args = -fopenmp" > site.cfg && echo "extra_link_args = -lopenblas" >> site.cfg && {{ PYTHON }} -m pip install . -vvv  # [osx or arm64]
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - llvm-openmp  # [osx or arm64]
    - libgomp      # [linux]
  host:
    - python
    - setuptools
    - pip
    - numpy
    - libblas * *openblas
    - openblas
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - pyyaml
    - matplotlib-base
    - h5py
    - phonopy >=2.21.0,<2.22.0
    - libblas * *openblas
    - openblas

test:
  imports:
    - phono3py
  source_files:
    - test
  commands:
    - pip check
    - pytest  # [linux]
    - pytest  # [osx and py>=38]
    - pytest  # [arm64 and py>=38]
  requires:
    - pytest

about:
  home: https://phonopy.github.io/phono3py
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A simulation package of phonon-phonon interaction related properties

  description: |
    This software calculates phonon-phonon interaction and related 
    properties using the supercell approach. 
  doc_url: https://phonopy.github.io/phono3py
  dev_url: https://github.com/phonopy/phono3py

extra:
  recipe-maintainers:
    - jan-janssen
    - jochym
    - atztogo
