{% set name = "phono3py" %}
{% set version = "2.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 45777cbfb2b4357a28348587ebb8c3599904594baa66f67ac9d2b35ee6151d4a

build:
  number: 1
  script: echo "[phono3py]" > site.cfg && echo "extra_compile_args = -fopenmp" >> site.cfg && echo "extra_link_args = -lgomp -lopenblas" >> site.cfg && {{ PYTHON }} -m pip install . -vv  # [linux]
  script: echo "[phono3py]" > site.cfg && echo "extra_compile_args = -fopenmp" >> site.cfg && echo "extra_link_args = -lopenblas" >> site.cfg && {{ PYTHON }} -m pip install . -vv  # [osx]
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - numpy
    - openblas
  host:
    - python
    - setuptools
    - pip
    - numpy
    - libblas * *openblas
    - openblas
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - pyyaml
    - matplotlib-base >=2.2.2
    - h5py
    - phonopy >=2.14.0,<=2.15.0
    - libblas * *openblas
    - openblas

test:
  imports:
    - phono3py
  source_files:
    - test
  commands:
    - pip check
    - pytest  # [linux]
    - pytest  # [osx and py>=38]
  requires:
    - pytest

about:
  home: https://atztogo.github.io/phono3py
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A simulation package of phonon-phonon interaction related properties

  description: |
    This software calculates phonon-phonon interaction and related 
    properties using the supercell approach. 
  doc_url: https://phonopy.github.io/phono3py
  dev_url: https://github.com/phonopy/phono3py

extra:
  recipe-maintainers:
    - jan-janssen
    - jochym
    - atztogo
