{% set name = "phono3py" %}
{% set version = "3.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0ba4816425795f59a9de986552e0ec797d47d0775946e4285febe9c0ef1fd387

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - llvm-openmp  # [osx or arm64]
    - libgomp      # [linux]
    - pip
    - scikit-build-core
    - nanobind
    - cmake
    - make  # [not win]
    - ninja  # [win]    
    - setuptools_scm
  host:
    - python
    - setuptools
    - numpy
    - libblas * *openblas
    - openblas
    - pip
    - scikit-build-core
    - nanobind
    - cmake
    - make  # [not win]
    - ninja  # [win]    
    - setuptools_scm
  run:
    - python
    - scipy
    - pyyaml
    - matplotlib-base
    - h5py
    - spglib
    - phonopy >=2.29.0,<2.30.0
    - libblas * *openblas
    - openblas

test:
  imports:
    - phono3py
  source_files:
    - test
  commands:
    - pip check
    - pytest -v
  requires:
    - pytest
    - pip

about:
  home: https://phonopy.github.io/phono3py
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A simulation package of phonon-phonon interaction related properties

  description: |
    This software calculates phonon-phonon interaction and related 
    properties using the supercell approach. 
  doc_url: https://phonopy.github.io/phono3py
  dev_url: https://github.com/phonopy/phono3py

extra:
  recipe-maintainers:
    - jan-janssen
    - jochym
    - atztogo
