bot:
  automerge: true
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
azure:
  settings_osx:
    pool:
      vmImage: macos-12
  store_build_artifacts: true
build_platform:
  osx_arm64: osx_64